### ISSUE TITLE
winapp driver is killed during UI tests execution

### ISSUE THREAD

**Issue by rafiaMushtaq** [microsoft/WinAppDriver#1883]
On local machine everything works fine. I am running tests on Azure pipeline. This error occurs randomly:
 
TearDown : OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4723
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
at System.Net.HttpWebRequest.GetRequestStream()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

Stack trace
at apvUITestsSetup.WaitForWebElement(String selector1, String selector2, Int32 findByType, Boolean desktop, Double timeout, Double pollInterval)
at autopipevesselUITests.Dialogs.MainDialog.get_MnFile()
at autopipevesselUITests.Dialogs.MainDialog.ClickFileOpen()
at autopipevesselUITests.ViewMenuTests.SetUp()
--TearDown
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.FindElements(String mechanism, String value)

i am using Visual Studio Test Platform Installer "Microsoft.TestPlatform 17.5.0" to run tests on VM
below are my nugget resources
    <NuGetSource Name="Microsoft.CodeCoverage" Version=" 17.4.0" />
    <NuGetSource Name="NUnit3TestAdapter" Version="3.17.0" />
    <NuGetSource Name="NUnit" Version="3.13.3" />
    <NuGetSource Name="Appium.WebDriver" Version="4.4.0" />
    <NuGetSource Name="Selenium.WebDriver" Version="3.141.0" />
![image](https://user-images.githubusercontent.com/61281438/228170575-9f5724a0-273f-4631-9eed-01367d4735b1.png)
![image](https://user-images.githubusercontent.com/61281438/228171055-c498441c-b69e-49bd-bfd3-f32f487f1ffc.png)

**Comment by anunay1** [comment]
I also could not root cause behind this error, as a stop gap arrangement, I implemented the solution to start and stop winappdriver through the code. Does the VM gets locked by any chance during the test execution?

**Comment by rafiaMushtaq** [comment]
yes I can lock VM, we also start and stop winappdriver in yaml file but it still crashes in middle. That' a random issue :-(
![image](https://user-images.githubusercontent.com/61281438/228445067-f7883fda-e132-4869-8a13-af6112653831.png)

**Comment by anunay1** [comment]
There is an issue which i observed some time back, the console message are buffered at time and it's not flushed which causes the winappdriver to crash.

**Comment by anunay1** [comment]
Yes.
