### ISSUE TITLE
failed to Locate 

### ISSUE THREAD

**Issue by sudeeppaudyal** [Microsoft/WinAppDriver#641]
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 241
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

HTTP/1.1 500 Internal Error
Content-Length: 169
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\Jericho\\JerichoLauncher.exe, and processId: 20108"}}

**Comment by sudeeppaudyal** [comment]
![Capture](https://user-images.githubusercontent.com/45410318/55115187-e13fd080-50b1-11e9-9885-784b1ef503d6.PNG)

**Comment by sudeeppaudyal** [comment]
Applications opens up after getting system.invalidOperationException.How to resolve this issue?

**Comment by CataUdrea** [comment]
Is there an update on the issue?
I am facing this same problem when trying to execute the WinAppDriver tests on Bamboo.
Locally the tests work OK.

**Comment by sudeeppaudyal** [comment]
@CataUdrea  How are you able to run locally?

**Comment by CataUdrea** [comment]
On my local machine, the tests are executed without any issues. I only get this problem when executing the tests on Bamboo.

I implemented the following steps:
- I start the winAppDriver
- define capabilities 
- launch the app

```
capabilities.setCapability("platformName", "Windows");
capabilities.setCapability("deviceName", "WindowsPC");
capabilities.setCapability("app", applicationUnderTest);
windowsApplicationDriver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
windowsApplicationDriver.launchApp();
```

I get the error from above only on Bamboo

**Comment by sudeeppaudyal** [comment]
I am still getting that error message.Would you mind sharing your email
address?

**Comment by sdhoka** [comment]
Any update on this issue? I'm running into similar issue when running tests in jenkins

**Comment by orion-test** [comment]
I am running into similar issue with jenkins.  Any updates would be great.

**Comment by jstTester** [comment]
I just reached this bug after sucesfully making few automated clicks work yesterday. Logging into app, having fun on login screen. Targeting proper .exe file as yesterday, nothing changed and yet application fails to start and I get same error as you:
[STDOUT] {"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: my path to .exe..

**Comment by lucas234** [comment]
I am running into a similar issue. I found a  temporary solution to figure out.
 ` try {
            driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), cap);
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), cap);
        }`

**Comment by nhhai** [comment]
Any update on this? I also have this, the tests run fine on my local with both `mvn` command in within Intellij IDE, but when I execute it on jenkins, it produces this. 

I set up my locale machine as a jenkins node and run on this node too, the problem persists though. I tried to get into the jenkins workspace on my local machine, and run the same command I ran on jenkins, and the tests run just fine. So this problem happens on jenkins only.

Please suggest at least a workaround for this.

**Comment by lucas234** [comment]
> Any update on this? I also have this, the tests run fine on my local with both `mvn` command in within Intellij IDE, but when I execute it on jenkins, it produces this.
> 
> I set up my locale machine as a jenkins node and run on this node too, the problem persists though. I tried to get into the jenkins workspace on my local machine, and run the same command I ran on jenkins, and the tests run just fine. So this problem happens on jenkins only.
> 
> Please suggest at least a workaround for this.

you can have a try to add try-catch. when some Exception happen, renew a driver instance, just a  try, it's suited for me

**Comment by jonwolfdev** [comment]
@lucas234 solution worked (try/catch).

See my releases logs it it helps... https://dev.azure.com/jonwolfdev/SimpleWPFTimer/_release?definitionId=1&view=mine&_a=releases

**Comment by benzionyunger** [comment]
I have a clean working solution in Java using the jna library to get the Native Window Handle dynamically and pass it to Desired Capabilities. You will need to use[ inspect.exe](https://docs.microsoft.com/en-us/windows/win32/winauto/inspect-objects) or another similar tool the first time to get the window name, but after that you're done. The only thing is, instead of launching your app with the WinAppSession you need to do it with a Process Builder and use the desired capability of "appTopLevelWindow" like this:

`ProcessBuilder pb = new ProcessBuilder();
            String folder  = "Users\\Myapp folder";
            pb.command(folder +"GEMS.exe");
            pb.start();
            Thread.sleep(7000);

            windowHandle = JNA_Test2.getHex();

            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("appTopLevelWindow", windowHandle);
            capabilities.setCapability("platformName", "Windows");
            capabilities.setCapability("deviceName","WindowsPC");
            GEMSDriver = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4728"), capabilities);

public class JNA_Test2 {

        public static String  getHex() {
            Pointer foundWindowPointer = new Memory(4096);
            JNA_Test2.isWindowOpen("_My app window name_", foundWindowPointer);
            String str = null;
            if (foundWindowPointer.getPointer(0) != null) {
                WinDef.HWND foundWindow = new WinDef.HWND(foundWindowPointer.getPointer(0));
                System.out.println("found window: " + foundWindow);
                str = String.valueOf(foundWindow);
                System.out.println("Native Window Handle: " + str.substring(7));
            }
            return str.substring(7);

        }
        public static void main(String []args){
            getHex();
        }

`

**Comment by balaji-githubstore** [comment]
Try to include below capability which solved my issue of Failed to locate opened application window with appId"xxx" and process "xxx"

My exe file present in C:\Program Files\MT

appCapabilities.SetCapability("appWorkingDir", "C:\Program Files\MT");

**Comment by anitakalyanasundaram** [comment]
Hi ,
Im also facing the similar issue. "Failed to locate opened application window with appId:" . sometimes its launched but not able to see the launched application. so getting "element not found " error.
Im trying to automate the applciaion that was developed by Eclipse RCP and launching the exe file to test.

**Comment by anitakalyanasundaram** [comment]
Run your WinApp driver and eclipse as an administrator. this solved my problem of launching the application.

**Comment by huster-songtao** [comment]
@sudeeppaudyal You can create WindowsDriver instance by NativeWindowHandle.

```
            // Create a session for Desktop
            DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
            desktopCapabilities.SetCapability("app", "Root");
            desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
            Assert.IsNotNull(desktopSession);

            // Launch Cortana Window using Windows Key + S keyboard shortcut to allow session creation to find it
            desktopSession.Keyboard.SendKeys(OpenQA.Selenium.Keys.Meta + "s" + OpenQA.Selenium.Keys.Meta);
            Thread.Sleep(TimeSpan.FromSeconds(1));
            WindowsElement CortanaWindow = desktopSession.FindElementByName("Cortana");
            string CortanaTopLevelWindowHandle = CortanaTopLevelWindowHandle = (int.Parse(CortanaWindow.GetAttribute("NativeWindowHandle"))).ToString("x");

            // Create session for already running Cortana
            DesiredCapabilities appCapabilities = new DesiredCapabilities();
            appCapabilities.SetCapability("appTopLevelWindow", CortanaTopLevelWindowHandle);
            cortanaSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
            Assert.IsNotNull(cortanaSession);

            // Set implicit timeout to 5 seconds to make element search to retry every 500 ms for at most ten times
            cortanaSession.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
```
