### ISSUE TITLE
Swipe/Scroll Support

### ISSUE THREAD

**Issue by ysabato** [Microsoft/WinAppDriver#93]
I would like to be able to scroll/swipe to element. At the moment, I am unable to accomplish this with latest release even though it states that touch was part of the v0.5-beta release. Am I doing it all wrong? My swipe command works for iOS but fails for Windows 10 desktop application. Can someone provide any working touch functionality script that I can use? I not sure what does and doesn't work. Thanks. 
"error": "unknown command",
"message": "Command not recognized:

**Comment by timotiusmargo** [comment]
Yes there were some issues with the swipe and scroll support on v0.5. These issues were addressed in v0.6 release and we also added more test cases such as https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/TouchScroll.cs. Please update and retry your case.

**Comment by dino-su** [comment]
I'm using v0.7-beta release and the TouchScroll case still doesn't works for me

I can see the touch/scroll command has been accepted by WinAppDriver but the Edge Browser doesn't scroll at all.

https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/TouchScroll.cs.
